name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test -- --passWithNoTests

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
        -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" 